# Site settings
email: fieldnoiseaudio@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/noise/page-:num"
google_analytics: 

# SEO settings
title: field noise - stories from the ambient world
description: a website and podcast exploring sound and the everyday
url: ""
twitter_username: fieldnoiseaudio
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  twitter: fieldnoiseaudio
  facebook: fieldnoisepodcast
  soundcloud: fieldnoiseaudio

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
